config/routes.rb
Rails.application.routes.draw do
  root 'budgets#index'

  resources :budgets do
    resources :works
  end

  get 'budgets/toprint/:id', to: 'budgets#toprint'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
    
    include Visible
    has_many :works, dependent: :destroy

    validates :cliente, presence: true
    validates :vehiculo, presence: true

end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
    
    VALID_STATUSES = ['public', 'private', 'archived']

    included do
        validates :status, inclusion: { in:VALID_STATUSES }
    end
    
    def archived?
        status == 'archived'
    end
end

app/models/work.rb
class Work < ApplicationRecord
  include Visible 

  belongs_to :budget
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

  def index
    http_basic_authenticate_or_request_with name: "oruga37", password: "luis1963"
    @budgets = Budget.all 
  end

  def show
    @budget = Budget.find(params[:id])
  end

  def new
    @budget = Budget.new
  end

  def create
    @budget = Budget.new(budget_params)
    if @budget.save
      redirect_to @budget
    else
      render :new
    end
    
  end

  def edit
    @budget = Budget.find(params[:id])
  end

  def update
    @budget = Budget.find(params[:id])
    if @budget.update(budget_params)
      redirect_to @budget
    else
      render :edit
    end
  end

  def destroy
    @budget = Budget.find(params[:id])
    @budget.destroy
    redirect_to root_path
    
  end

  def toprint
    @budget = Budget.find(params[:id])
       
  end

  private
    def budget_params
      params.require(:budget).permit(:cliente,:vehiculo, :status)
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
    def create
        @budget = Budget.find(params[:budget_id])
        @work = @budget.works.create(work_params)
        redirect_to budget_path(@budget)
    end

    def destroy
        @budget = Budget.find(params[:budget_id])
        @work = @budget.works.find(params[:id])
        @work.destroy
        redirect_to budget_path(@budget)
        
    end

    private
    def work_params
        params.require(:work).permit(:trabajo,:precio, :status)
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/budgets/_form.html.erb
<%= form_with model: budget do |form| %>
    <div class="card">
        <div class="card-body">
            
            <div class="mb-3">
                <h3>
                    <%= form.label :cliente, {class:"form-label"}%> <br>
                </h3>
                <%= form.text_field :cliente, {class: "form-control", placeholder:"Nombre del cliente"}%>
                <%@budget.errors.full_messages_for(:cliente).each do |message|%>
                    <div>
                        <%= message%>
                    </div>
                <% end%>   
            </div>
            <div class="mb-3">
                <h3>
                    <%= form.label :vehiculo, {class:"form-label"}%>
                </h3>
                <%= form.text_field :vehiculo, {class:"form-control", placeholder:"Marca y Modelo del vehiculo"}%>
                <%@budget.errors.full_messages_for(:cliente).each do |message|%>
                    <div>
                        <%= message%>
                    </div>
                <% end%>   
            </div>
            <div class="mb-3 d-none">
                <%= form.label :status, 'Permiso'%>
                <%= form.select :status, ['public','private','archived'], selected:'public'%> <br>   
            </div>
            <div class="d-grip">
                <%= form.submit "Enviar", {class:"btn btn-warning col-12"}%>
            </div>                  
        </div>      
    </div>
<% end %>
<div class="d-grip">
    <%= link_to "Salir", '/', {class:"btn btn-danger col-3"}%>
</div>

app/views/budgets/edit.html.erb
<h1>
Modificando
</h1>

<%= render 'form', budget: @budget%>

app/views/budgets/index.html.erb
<div class="container py-4 my-3 border text-center">
  <h1> Archivo</h1>

  <table class="table my-5">
    <thead>
      <tr>
        <th scope="col">Cliente</th>
        <th scope="col">Vehiculo</th>
        <th scope="col">Fecha</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @budgets.each do |budget| %>
        <tr>
          <th scope="row">
              <%= budget.cliente%>
          </th>
          <td>
              <%= budget.vehiculo%>
          </td>
          <td>
              <%= budget.created_at.to_date%>
          </td>
          <td>
            <div class="row">
              <div class="col-md-5 d-none d-sm-block">
                 <%= link_to "Ver", budget, {class:"btn btn-primary col-md-12"}%>
              </div>
              <div class="col-md-5 d-none d-sm-block">
                 <%= link_to "Eliminar", budget_path(budget),method: "delete",  class:"btn btn-danger col-md-12 col-xs-0"%>
              </div>
            </div>
            <%# BOTONES EN MODO RESPONSIVO %>
            <div class="row d-block d-sm-none">
              <div class="d-grid col-6 px-0">
                <span>
                  <%= link_to "Ver", budget, {class:"btn btn-primary btn-sm my-1 col-md-12 col-xs-0"}%>  
                </span>
                <span>
                  <%= link_to "Eliminar", budget_path(budget),method: "delete",  class:"btn btn-danger btn-sm col-md-12 "%>
                </button>
              </div>
            </div>
          </td>
        </tr>  
      <% end %>


    
    </tbody>
  </table>
        <%= link_to "Nuevo Presupuesto", new_budget_path, {class:"btn btn-warning"}%>

</div>

app/views/budgets/new.html.erb
<h1 class="my-4">
Nuevo cliente
</h1>
<%= render "form" , budget: @budget%>

app/views/budgets/show.html.erb
<div class="row">
    <div class="col-md-8 col-sm-12 my-3">
        <div class="text-center">
            <h1>
                <%= @budget.cliente%>
            </h1>
            <h2>
                <%= @budget.vehiculo%>
            </h2>
            <p>
                <%= @budget.created_at.to_date%>
            </p>
            <p>
                <%= link_to "Editar", edit_budget_path(@budget)%>
            </p>
        </div>
        <table class="table table-striped table-responsive">
            <thead>
                <tr>
                    <th scope="col" class="col-9"> Trabajo </th>
                    <th scope="col" class="col-3"> Valor</th>   
                </tr>
            </thead>

            <tbody>
                <%@budget.works.each do |work|%>
                <tr>
                    <td>
                    <%= work.trabajo%>
                    </td>
                    <td>
                    <%= number_to_currency(work.precio, precision:0)%>
                    <%= link_to 'Eliminar', [work.budget, work],
                        {method: :delete,
                        data: {confirm:"Estas seguro?"},
                        class:"btn btn-danger"}%>
                    </td>
                    
                </tr>
                <%end%>
            </tbody>   
            <tfoot>
                <tr>
                    <th scope="row">
                        Total
                    </td>
                    <td>
                        <%=number_to_currency(@budget.works.sum(:precio), precision: 0)%>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        Iva
                    </td>
                    <td>
                        <%=number_to_currency(@budget.works.sum(:precio)-(@budget.works.sum(:precio)/1.19), precision:0)%>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        Total Neto
                    </td>
                    <td>
                        <%=number_to_currency(@budget.works.sum(:precio)*1.19, precision:0)%>
                    </td>
                </tr>
            </tfoot> 
            
        </table>
    </div>

    <div class="col-md-4 col-sm-12 my-3">
        <%= render 'works/form'%>
        <%= link_to "Ir al Archivo", '/', {class:"btn btn-primary col-12 my-3"}%>        
        <%= link_to "Vista Previa", {action: "toprint"}, id:@budget, class:"btn btn-success col-12 my-3"%>
        

        <%= link_to "Eliminar Presupuesto", budget_path(@budget), method: :delete, data:{confirm: "Estas seguro?"}, class:"btn btn-danger col-12" %>
        </div>

    </div>
    
</div>

app/views/budgets/toprint.html.erb
        <div class="row">
            <div class="col-md-4">
            </div>

            <div class="col-md-4 col-xs-12 text-center">
                <h1>
                <%= @budget.cliente%>
                </h1>
                <h2>
                    <%= @budget.vehiculo%>
                </h2>
                <p>
                    <%= @budget.created_at.to_date%>
                </p>
            </div>
            
            <div class="col-md-4 ">
            </div>
        </div>
        
        


        <div class="text-center">
            
        </div>
        <table class="table table-striped table-responsive">
            <thead>
                <tr>
                    <th scope="col" class="col-9"> Trabajo </th>
                    <th scope="col" class="col-3"> Valor</th>   
                </tr>
            </thead>

            <tbody>
                <%@budget.works.each do |work|%>
                <tr>
                    <td>
                    <%= work.trabajo%>
                    </td>
                    <td>
                    <%= number_to_currency(work.precio, precision:0)%>
                    </td>
                    
                </tr>
                <%end%>
            </tbody>   
            <tfoot>
                <tr>
                    <th scope="row">
                        Total
                    </td>
                    <td>
                        <%=number_to_currency(@budget.works.sum(:precio), precision: 0)%>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        Iva
                    </td>
                    <td>
                        <%=number_to_currency(@budget.works.sum(:precio)-(@budget.works.sum(:precio)/1.19), precision:0)%>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        Total Neto
                    </td>
                    <td>
                        <%=number_to_currency(@budget.works.sum(:precio)*1.19, precision:0)%>
                    </td>
                </tr>
            </tfoot>             
        </table>
    </div>
    <div class="row">
        <div class="col-md-4 col-xs-4">
        </div>
        <div class="col-md-4 col-xs-4">
            <a href="/">
                <img src="http://oruga37.cl/wp-content/uploads/2020/07/oruga-isotipodf.jpg" class="img-thumbnail">
            </a>
        </div>
        <div class="col-md-4 col-xs-4">
        </div>
    
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PresupuestosV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/works/_form.html.erb
<%=form_with model: [@budget, @budget.works.build] do |form|%>
     <div class="card">
        <div class="card-body">
            <h5 class="class-title">
                Agregar nuevo trabajo
            </h5>
            <%=form.label :trabajo, "Trabajo", {class:"form-label"}%>
            <%=form.text_field :trabajo ,{class:"form-control"}%>
            <p>
                <%=form.label :precio, "Precio", {class:"form-label"}%>
                <%=form.number_field :precio, {class:"form-control"} %>
            </p>
            <p class="d-none">
                <%=form.label :status, "Permiso", {class:"form-label"}%>
                <%=form.select :status,['public','private','archived'], selected:'public' %>
            </p>

            <div>
            <%= form.submit "Agregar" , {class:"btn btn-warning"}%>
            </div>
        </div>
        
     </div>

<%end%>